### ISSUE TITLE
Add documentation about libraries or techniques that are being use in the template

### ISSUE THREAD

**Issue by lydiasama** [nimblehq/flutter-templates#180]
## Why

When I was learning Flutter as a new joiner, I discovered that we use [flutter_gen](https://pub.dev/packages/flutter_gen) to generate the asset path. However, there is no official documentation that mentions this. The Flutter Training Path that we follow only refers to this document: https://docs.flutter.dev/development/ui/assets-and-images. Therefore, having proper documentation can help new joiners to become familiar with our conventions and techniques more easily.

The slack discussion is [here](https://nimble-co.slack.com/archives/C01NKCFNE6R/p1680508216711269).
 
## Who Benefits?

Developers

**Comment by sleepylee** [comment]
Learning is part of a developer's role rather than the responsibility of the Maintainer of this project. 

Having an instruction about running the command: `flutter packages pub run build_runner build` is necessary I agree, we can add it, but asking for all lib usages is too much to handle. We are not doing it in any project.

**Comment by luongvo** [comment]
@lydiasama I added some helpful information to the template's supported features & libraries in this PR https://github.com/nimblehq/flutter-templates/pull/238. It somehow helps resolve your concern here. I agree with Trung that we should not put deep documentation of each library at this template level.
